name: 'Docker Build & Push'
description: 'Login to Docker registry, build Docker image, and push it'

inputs:
  username:
    description: 'Docker registry username'
    required: true
  password:
    description: 'Docker registry password'
    required: true
  image:
    description: 'Docker image name (without tag)'
    required: true
  tag:
    description: 'Docker image tag'
    required: false
    default: 'latest'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Build context directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: dcr.oskadev.com
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build Docker image
      shell: bash 
      run: |
        docker build -f ${{ inputs.dockerfile }} -t dcr.oskadev.com/${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.context }}

    - name: Push Docker image
      shell: bash 
      run: |
        docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
